### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by rlebron-bioinfo** [gear-genomics/teal#13]
Hi, 

Thank you for this interesting project. Since you have to start the server and client separately, I would like to know if it is possible to deploy this project on Heroku. Any hints on how to do the deployment would be welcome.

Thanks in advance.

Best regards,
Ricardo Lebrón

**Comment by tobiasrausch** [comment]
There is running web application of teal that you can directly use: [www.gear-genomics.com/teal](www.gear-genomics.com/teal)

**Comment by rlebron-bioinfo** [comment]
Thanks for the information, but I would like to deploy my own instance so I can customize it.

**Comment by tobiasrausch** [comment]
Sure, the code is open source and you are welcome to do this. We don't have any development plans to deploy this project on Heroku.
